### ISSUE TITLE
[Feat] SearchBar+TableView (실시간검색) 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-SAEBBING#12]
## Todo
- [x] UISearchBar + UITableView로 UI 구현
- [ ] ViewModel에 모델 및 비즈니스 로직 구현
- [ ] 실시간 검색 구현 (RxCocoa 사용)
