### ISSUE TITLE
[UI] Expandable View UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-SAEBBING#23]
## Todo

- [x] 경로 상세 UI 구현 
- [x] CellType 분기처리 
- [x] Cell UI 구현 
- [ ] Mock 데이터 바인딩 
- [x] 버스 경로 expand cell 구현
