### ISSUE TITLE
[Feat] 추천 경로 상세 UI 및 기능 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-SAEBBING#25]
## Todo

- [ ] 추천 경로 상세 UI 완성 (세부 UI 및 Mock 데이터 바인딩 구현)
- [ ] Expandable 상태 분기처리 
- [ ] Cell 재사용 
- [ ] 실선, 점선, 아이콘 UI 구현
