### ISSUE TITLE
[UI] 사진 리스트 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-SAEBBING#3]
## Todo

- [x] /phots API로 받아온 데이터 -> 사진 리스트 UI 구현
- [x] 리스트 선택 후 사진 상세 UI 구현 (데이터 전달 후 서버 통신)
- [x] MVVM + DiffableDataSource + CompositionalLayout 사용 
- [ ] Pagination 구현
